### PR TITLE
Faiss integration

### PR DESCRIPTION
**Pull request by Natlem**
Hey,

Here the pull request for faiss integration that comes with the handling of custom KNN.
Summary:
 - Add FAISS (https://github.com/facebookresearch/faiss)
 - Add handling of custom knn

### CODE REVIEW

**Comment by luizgh** [comment]
@Natlem Thanks for the pull request. Please update the docstrings to describe the new parameter as "knn_classifier: The algorithm used to estimate the region of competence" or something similar (@Menelau may have a better wording for it / better name for this parameter). Also, please set the default to "knn" instead of None.

We also need to update methods META-DES and KNOP that create another knn (on the output profiles space) to also use the method that was selected (one way of doing this is to store the class in ```self.roc_constructor```, and then using it later like ```self.roc = self.roc_constructor(k)```).

We should do some performance tests to make sure that integrating the FAISS code is worth it. We also need to update the documentation to specify it as an optional requirement, and direct the user on how to install it

**Comment by Menelau** [comment]
@Natlem Thanks for the pull request. I think the only thing missing now is setting knn_classifier to knn instead of None and updating the docstring as @luizgh mentioned. In the case I agree with him with the description:

"knn_classifier: The algorithm used to estimate the region of competence."
 
Just need to add in the description that if knn_classifier = None, the KNeighborsClassifier from sklearn is used.

@luizgh Yes, we should do some performance test. In fact, it would be nice to have one example using the library for processing a larger dataset using the Faiss KNN. And you are right we need to mention that this is an optional requirement in the documentation.

We also gonna need some unit test using the Faiss knn instead of sklearn nearest neighbors. But that can come in a new pull request.

**Comment by Natlem** [comment]
> setting knn_classifier to knn instead of None and updating the docstring as
I will update this as soon as possible 

> @luizgh Yes, we should do some performance test. In fact, it would be nice to have one example using the library for processing a larger dataset using the Faiss KNN
The experiment is started. I will keep you up to date.

> We also gonna need some unit test using the Faiss knn instead of sklearn nearest neighbors. But that can come in a new pull request.
Probably yeah.

**Comment by Natlem** [comment]
We also need to update to documentation for install as well for the FAISS (I wonder where we should put it though)

**Comment by Menelau** [comment]
@Natlem I believe it should be included in the User Guide/Installation section.

In the case, it is important to mention that Faiss installation is optional. Also, we can mention that Faiss KNN is only supported on Linux and MacOs

**Pull request merged**
